import numpy as np
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dataset import BraggNNDataset

NUM_PATCHES = 10
PSZ = 11
OUTPUT_FILE = "braggnn_inputs.h"


def format_c_array(name, data):
    h, w = data.shape
    lines = []
    lines.append(f"static float {name}[{h}][{w}] = {{")
    for r in range(h):
        vals = ", ".join(f"{v:.6f}f" for v in data[r])
        lines.append(f"  {{{vals}}},")
    lines.append("};")
    return "\n".join(lines)


def main():
    print(f"Loading BraggNN validation dataset (psz={PSZ})...")
    ds = BraggNNDataset(psz=PSZ, rnd_shift=0, use='validation')
    print(f"Dataset size: {len(ds)} patches")

    indices = np.linspace(0, len(ds) - 1, NUM_PATCHES, dtype=int)

    sections = []
    sections.append("#ifndef BRAGGNN_INPUTS_H")
    sections.append("#define BRAGGNN_INPUTS_H")
    sections.append("")
    sections.append("// Auto-generated by export_input_patches.py")
    sections.append(f"// {NUM_PATCHES} input patches from BraggNN validation set")
    sections.append(f"// Patch size: {PSZ}x{PSZ}, FP32 normalized [0,1]")
    sections.append("")
    sections.append(f"#define NUM_TEST_PATCHES {NUM_PATCHES}")
    sections.append(f"#define PATCH_SIZE {PSZ}")
    sections.append("")

    patches = []
    labels = []

    for i, idx in enumerate(indices):
        feat, label = ds[int(idx)]  # feat: (1, 11, 11), label: (2,)
        patch = feat[0]  # (11, 11)
        patches.append(patch)
        labels.append(label)
        print(f"  Patch {i}: idx={idx}, range=[{patch.min():.4f}, {patch.max():.4f}], "
              f"label=({label[0]:.4f}, {label[1]:.4f})")

    # Input patches
    sections.append("// ============================================")
    sections.append("// FP32 Input Patches")
    sections.append("// ============================================")
    sections.append("")

    for i in range(NUM_PATCHES):
        sections.append(f"// Patch {i}: dataset index {indices[i]}")
        sections.append(format_c_array(f"test_input_{i}", patches[i]))
        sections.append("")

    ptrs = ", ".join(f"(float *)test_input_{i}" for i in range(NUM_PATCHES))
    sections.append(f"static float *test_inputs[NUM_TEST_PATCHES] = {{{ptrs}}};")
    sections.append("")

    # Labels (scaled to pixel coordinates)
    sections.append("// ============================================")
    sections.append(f"// Expected Labels (pixel coordinates in {PSZ}x{PSZ} patch)")
    sections.append("// ============================================")
    sections.append("")

    for i in range(NUM_PATCHES):
        lx = labels[i][0] * PSZ
        ly = labels[i][1] * PSZ
        sections.append(f"static float test_label_{i}[2] = {{{lx:.6f}f, {ly:.6f}f}};")

    sections.append("")
    labels_arr = ", ".join(f"test_label_{i}" for i in range(NUM_PATCHES))
    sections.append(f"static float *test_labels[NUM_TEST_PATCHES] = {{{labels_arr}}};")

    sections.append("")
    sections.append("#endif // BRAGGNN_INPUTS_H")
    sections.append("")

    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), OUTPUT_FILE)
    with open(output_path, "w") as f:
        f.write("\n".join(sections))

    print(f"\nWrote {output_path}")


if __name__ == "__main__":
    main()
